### ISSUE TITLE
 Symbol’s function definition is void: t when trying both examples in examples.org

### ISSUE THREAD

**Issue by maxandersen** [alphapapa/org-sidebar#6]
when I try the two examples in examples.org in the first example I get:

` Symbol’s function definition is void: t`

and in second example I get the following error:

`Error: Keyword argument <= not one of (:from :to :on)`

**Comment by alphapapa** [comment]
Thanks, I forgot to update the examples when I changed `org-ql`.  Should be fixed now.

**Comment by maxandersen** [comment]
hmm - I recopied the content again from examples.org and I'm still seeing the errors :/

**Comment by alphapapa** [comment]
Works for me.

**Comment by alphapapa** [comment]
@maxandersen As I posted on Reddit just now:

I just tested the whole thing from scratch in a clean Emacs configuation on Emacs 26.2.  The first example works without errors.

Try to reproduce in a clean Emacs config.  It should work correctly.

You're probably suffering from stale `.elc` files somewhere in your `elpa` directory.  You should probably reinstall all packages from scratch (because if you just delete all `.elc` files, none of them will be byte-compiled anymore).
